export { default as Table } from "./table.astro"
export { default as TableBody } from "./table-body.astro"
export { default as TableCell } from "./table-cell.astro"
export { default as TableHead } from "./table-head.astro"
export { default as TableHeader } from "./table-header.astro"
export { default as TableRow } from "./table-row.astro"
